# Generated by Django 5.2.6 on 2025-10-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('wild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='wild.snake'),
        ),
    ]
