# Generated by Django 5.2.6 on 2025-10-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('common_names', models.TextField(blank=True, null=True)),
                ('venom_type', models.CharField(choices=[('venomous', 'Venomous'), ('mildly_venomous', 'Mildly Venomous'), ('non_venomous', 'Non-Venomous')], max_length=50)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_translation', models.TextField(blank=True, null=True)),
                ('habitats', models.ManyToManyField(related_name='snakes', to='wild.habitat')),
                ('regions', models.ManyToManyField(related_name='snakes', to='wild.region')),
            ],
        ),
        migrations.CreateModel(
            name='SnakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='snakes/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('snake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wild.snake')),
            ],
        ),
    ]
